version: '3.9'

services:

  # DEFEND
  nginx-defender:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "80:80/udp"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs/access.log:/var/log/nginx/access.log
      - ./nginx/logs/error.log:/var/log/nginx/error.log

  # Simulate normal load with siege
  siege:
    image: yokogawa/siege
    command: siege -d10 -c100 -t1H http://nginx-defender/
    depends_on:
      - nginx-defender

  # MONITOR
  goaccess:
    image: allinurl/goaccess
    restart: unless-stopped
    ports:
      - "7890:7890"
    volumes:
      - data:/srv/data
      - logs:/srv/logs
      - report:/srv/report
      - ./nginx/logs/access.log:/srv/logs/access.log:ro
      - ./nginx/logs/error.log:/srv/logs/error.log:ro
      - ./goaccess/goaccess.conf:/srv/data/goaccess.conf:ro
    command: ["--no-global-config", "--config-file=/srv/data/goaccess.conf"]
    depends_on:
      - nginx-defender

  nginx-goaccess:
    image: nginx
    restart: unless-stopped
    container_name: goaccess_nginx
    ports:
      - "8080:80"
    volumes:
      - report:/usr/share/nginx/html
      - ./goaccess/goaccess-nginx.conf:/etc/nginx/conf.d/default.conf:ro

  influxdb:
    image: influxdb:latest
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: vlad
      DOCKER_INFLUXDB_INIT_PASSWORD: vladvlad
      DOCKER_INFLUXDB_INIT_ORG: org
      DOCKER_INFLUXDB_INIT_BUCKET: bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: VJEFSpiu1pUN38unLpIyjyFIYnrt3cyIt9twF8VgffNihQsN2b5ghS3w6FLkZaqvEmmhxYaU9xBuJBX1exDFvQ==
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2

  telegraf:
    image: telegraf:latest
    user: "root:1001"
    restart: always
    depends_on:
      - influxdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx/logs/access.log:/var/log/nginx/access.log:ro
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf


  # ATTACK
  http-flood-attack:
    image: utkudarilmaz/hping3:latest
    command: --flood --rand-source -p 80 nginx-defender
    profiles:
      - attacks

  tcp-syn-flood-attack:
    image: utkudarilmaz/hping3:latest
    command: --flood --rand-source -S -q -n -p 80 nginx-defender
    profiles:
      - attacks

  udp-flood-attack:
    image: utkudarilmaz/hping3:latest
    command: --flood --rand-source --udp -p 80 nginx-defender
    profiles:
      - attacks

  tcp-fin-flood-attack:
    image: utkudarilmaz/hping3:latest
    command: --flood --rand-source -F -p 80 nginx-defender
    profiles:
      - attacks

  tcp-rst-flood-attack:
    image: utkudarilmaz/hping3:latest
    command: --flood --rand-source -R -p 80 nginx-defender
    profiles:
      - attacks

  tcp-push-and-ack-flood-attack:
    image: utkudarilmaz/hping3:latest
    command: --flood --rand-source -PA -p 80 nginx-defender
    profiles:
      - attacks

  icmp-flood-attack:
    image: utkudarilmaz/hping3:latest
    command: --flood --rand-source -1 -p 80 nginx-defender
    profiles:
      - attacks


volumes:
  data: {}
  logs: {}
  report: {}
  grafana_data: {}
  influxdb_data: {}